### ISSUE TITLE
How can we then export created Excalidraw files to native Excalidraw app/website? 

### ISSUE THREAD

**Issue by myownstandard** [haydenull/logseq-plugin-excalidraw#10]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Hi!
Is there a way to move the files created with Excalidraw Plugin and reuse them on the https://excalidraw.com (to continue working with them not using Logseq app)?
Are they saving in common Excalidraw file type supported by the official https://excalidraw.com plugin? 
Thank you!

### Reproduce the Bug

How to reuse created Excalidraw files?
If i go to Logseq vault/pages and pull some file like excalidraw-2023-05-25-16-23-08 how can then i use it outside the Logseq?

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
You can choose "Embed scene" when exporting image. Then you can use htpps://excalidraw.com to edit this image file.

<img width="1456" alt="image" src="https://github.com/haydenull/logseq-plugin-excalidraw/assets/17695989/d8d43ca3-bd6f-4a3c-99d6-1f97c26602be">

<img width="986" alt="image" src="https://github.com/haydenull/logseq-plugin-excalidraw/assets/17695989/a975eede-4841-4866-8a07-c0db35b49fb6">

**Comment by myownstandard** [comment]
Many thanks!! I think that info worth adding to  Readme section of the plugin in my humble opinion 🙂
