### ISSUE TITLE
Feature Request: Saved pan/zoom and view mode

### ISSUE THREAD

**Issue by nichodges** [haydenull/logseq-plugin-excalidraw#16]
Thanks for the amazing plugin. 

Just wondering if it would be possible to save the view of a drawing (i.e. where it is panned to and what the zoom level is), and also whether view mode is on or off?

The use case here is that I'll often have one big drawing for a project, and then I'll be writing in Logseq about the project and want to include sections of the drawing in a specific part of the page. 

My current solution is to just PNG that section of the drawing and drop it into the Logseq page, but obviously I need to re-do that if I change the drawing.

Thanks again for the plugin.

**Comment by haydenull** [comment]
You can given version 1.4.0 a try. Feel free to reach out if you have any questions.
