### ISSUE TITLE
How to link diagram created in the Dashboard view?

### ISSUE THREAD

**Issue by ppggff** [haydenull/logseq-plugin-excalidraw#19]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Step:
1. Create a diagram in Dashboard view
2. Then rename it to xxx
3. Then try to link it in a page by `{{renderer excalidraw, xxx}}`
4. It shows 'Page Not Found'

The how to link it, or how to find the 'real' name of it?

### Reproduce the Bug

1. Create a diagram in Dashboard view
2. Then rename it to xxx
3. Then try to link it in a page by `{{renderer excalidraw, xxx}}`
4. It shows 'Page Not Found'

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
`{{renderer excalidraw, excalidraw-2023-04-29-17-02-53}}`
excalidraw-2023-04-29-17-02-53 is the name of your file

**Comment by ppggff** [comment]
Where to find the file name? Hopefully it can be found on the dashboard page.

**Comment by haydenull** [comment]
You can upgrade to version 1.4.1, and then click `Copy Renderer Text` on the context menu.

<img width="992" alt="image" src="https://github.com/haydenull/logseq-plugin-excalidraw/assets/17695989/6496776d-4e47-41c3-85e5-359cbb345f56">

**Comment by ppggff** [comment]
It works 👍
