### ISSUE TITLE
how is this different than /Draw

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [haydenull/logseq-plugin-excalidraw#2]
Hi!

I'm wondering something about your project and think you might want to add the answer to the README.md as I don't think I'll be the only one :)

What are the difference between this plugin and /Draw? Same question with whiteboards?

Thanks and have a nice day!

**Comment by haydenull** [comment]
The reason for developing this plugin is that the excalidraw build-in with logseq cannot meet my needs, such as preview and full-screen operation.

I hope this plugin can help users easily showcase their ideas, so it needs to have the following features:

- full-screen operation
- customize drawing name (in development)
- drawing management dashboard (in development)

Another point is that the plugin will remain synchronized with the official version of Excalidraw.

**Comment by thiswillbeyourgithub** [comment]
Alright! Great idea and project thanks a lot.

That's really too bad there is no search function yet in excalidraw. There are [many PR adding search](https://github.com/excalidraw/excalidraw/pulls?q=is%3Apr+is%3Aopen+search) but AFAIK none have been merged yet. Can't wait as I'm thinking of creating a link between mindmaps (via excalidraw) and logseq flashcards automatically using ML stuff.
