### ISSUE TITLE
Buttons in the editor view are blocked by the system's title bar

### ISSUE THREAD

**Issue by ppggff** [haydenull/logseq-plugin-excalidraw#22]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The buttons in the editor view are blocked by the system's title bar. You can see it, but you can only click on the bottom half of the button.

### Reproduce the Bug

1. Open the editor view
2. Try to click button such as 'Line'

### Environment Information

macOS 13.5.1
logseq 0.9.15
plugin 1.4.0

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by haydenull** [comment]
This issue needs to be addressed by logseq, I have already raised an issuehttps://github.com/logseq/logseq/issues/10043 for it.

**Comment by haydenull** [comment]
this issue has been addressed in version 1.5.1. You can have a try.
