### ISSUE TITLE
与Awesome UI与tabs插件UI冲突

### ISSUE THREAD

**Issue by OriOYue** [haydenull/logseq-plugin-excalidraw#6]
如图：
在同时启用Awesome UI插件与Tabs插件时，界面UI会与excalidraw冲突，只启用其中一个插件倒是不会冲突：
![1683441941293](https://user-images.githubusercontent.com/72482686/236662298-93b2fe51-83b0-4ba0-9893-177ab4a75ed2.png)

**Comment by haydenull** [comment]
主要是与 awesome ui 冲突了，我调高了插件 ui 的层级，可以试试 1.3.0 版本
