### ISSUE TITLE
Dark Mode Preview + Preview options

### ISSUE THREAD

**Issue by CactiChameleon9** [haydenull/logseq-plugin-excalidraw#8]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When using this plugin with logseq dark mode I would expect the previews to be dark

An option for transparent backgrounds (like when you export a drawing to png) would be good also

### Reproduce the Bug

1. Make a drawing with this plugin
2. Be in dark mode

**Comment by haydenull** [comment]
You can try version 1.3.0 .
